### ISSUE TITLE
空指针

### ISSUE THREAD

**Issue by githubliruiyuan** [Meiqia/MeiqiaSDK-Android#107]
Caused by:
java.lang.NullPointerException:
com.meiqia.meiqiasdk.activity.MQPhotoPreviewActivity$ImagePageAdapter.getCount(MQPhotoPreviewActivity.java:279)
android.support.v4.view.ViewPager.setAdapter(ViewPager.java:495)
com.meiqia.meiqiasdk.activity.MQPhotoPreviewActivity.processLogic(MQPhotoPreviewActivity.java:142)
com.meiqia.meiqiasdk.activity.MQPhotoPreviewActivity.onCreate(MQPhotoPreviewActivity.java:102)

**Comment by bingoogolapple** [comment]
@githubliruiyuan 有改过「MeiqiaSDK-Android」的源码吗？

如果没有改过源码，是聊天界面预览图片时报这个错？还是留言表单界面预览图片时报这个说？

**Comment by githubliruiyuan** [comment]
应该是给过源码的
