### ISSUE TITLE
6.0权限处理问题

### ISSUE THREAD

**Issue by pscj** [Meiqia/MeiqiaSDK-Android#108]
当客户app用的是targetSdkVersion在23以下时候，引用你们的sdk，sdk的权限处理代码用的是新的，此时调用ContextCompat.checkSelfPermission，会出现，无法继续下去的问题。  应该加入判断代码，23以下直接按已经授权的逻辑走。。。一个场景就是点击会话窗口的voice按钮，没反应

**Comment by bingoogolapple** [comment]
@pscj 指定compileSdkVersion为23，targetSdkVersion随便你用哪一个

**Comment by pscj** [comment]
忘加audio权限了，现在可以了
