### ISSUE TITLE
建议 隐藏SDK内部的资源

### ISSUE THREAD

**Issue by qiyulan** [Meiqia/MeiqiaSDK-Android#111]
AS 1.3起就支持 library 隐藏私有资源
建议隐藏 SDK 的资源,开发者在使用时不会看到一堆mq_开头的资源了.

具体参见 https://www.youtube.com/watch?v=_Rox-HXhRfI&feature=youtu.be&t=144

**Comment by ksxkq** [comment]
将会在 v3.4.6 版本中优化
