### ISSUE TITLE
几个异常问题

### ISSUE THREAD

**Issue by githubliruiyuan** [Meiqia/MeiqiaSDK-Android#117]
java.lang.ClassCastException
com.meiqia.meiqiasdk.widget.MQClientItem cannot be cast to com.meiqia.meiqiasdk.widget.MQRobotItem
com.meiqia.meiqiasdk.util.MQChatAdapter.getView(MQChatAdapter.java:139)

java.lang.RuntimeException
请调用MQConfig.init方法初始化美洽 SDK，并传入MQImageLoader接口的实现类
com.meiqia.meiqiasdk.util.MQConfig.getImageLoader(MQConfig.java:78)
com.meiqia.meiqiasdk.widget.MQAgentItem.setMessage(MQAgentItem.java:47)
com.meiqia.meiqiasdk.util.MQChatAdapter.getView(MQChatAdapter.java:133)

java.lang.SecurityException
ConnectivityService: Neither user 10208 nor current process has android.permission.ACCESS_NETWORK_STATE.
java.lang.RuntimeException:Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in com.meiqia.core.ce@ac8f0e7
android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:874)
......
Caused by:
java.lang.SecurityException:ConnectivityService: Neither user 10208 nor current process has android.permission.ACCESS_NETWORK_STATE.
android.os.Parcel.readException(Parcel.java:1540)
android.os.Parcel.readException(Parcel.java:1493)
android.net.IConnectivityManager$Stub$Proxy.getActiveNetworkInfo(IConnectivityManager.java:968)
android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:614)
com.meiqia.core.b.l.f(Unknown Source)
com.meiqia.core.ce.onReceive(Unknown Source)

**Comment by bingoogolapple** [comment]
@githubliruiyuan 请用最新的3.2.5版
