### ISSUE TITLE
soundPool异常

### ISSUE THREAD

**Issue by pscj** [Meiqia/MeiqiaSDK-Android#118]
Could not find class 'android.media.SoundPool$Builder', referenced from method com.meiqia.meiqiasdk.util.MQSoundPoolManager.<init>
在android4.4.4的红米上会报这个错。原因是这个Builder的api level是21

**Comment by bingoogolapple** [comment]
@pscj 你用的是哪个版本的「美洽 SDK」？

**Comment by pscj** [comment]
3.2.2

**Comment by bingoogolapple** [comment]
```
    private MQSoundPoolManager(Context context) {
        this.mContext = context;
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            mSoundPool = new SoundPool.Builder().setMaxStreams(STREAMS_COUNT).build();
        } else {
            mSoundPool = new SoundPool(STREAMS_COUNT, AudioManager.STREAM_MUSIC, 0);
        }
        mAudioManager = (AudioManager) context.getSystemService(Context.AUDIO_SERVICE);
        mSoundSourceMap = new HashMap<>();
    }
```

「美洽 SDK」里是有判断api level21的，不晓得是不是红米定制过的，你那边方便clone「美洽 SDK」源码下来测试一下吗

**Comment by pscj** [comment]
因为用的插件化框架 我就是用源码编译的，我调一下试试看

**Comment by pscj** [comment]
1 public static MQSoundPoolManager getInstance(Context context) {
2        return new MQSoundPoolManager(context.getApplicationContext());
3 }
真是个诡异的问题，断点在第2行还没执行的时候，log就已经输出那个错误信息了。
测试了下官方的demo,也是同样的问题，表现就是进去客服界面，里面的 声音都放不出来了。设备是红米Note 1S
