### ISSUE TITLE
Changing Send Button Color

### ISSUE THREAD

**Issue by mahmed8003** [Meiqia/MeiqiaSDK-Android#142]
Whenever I start to type in textbox at bottom of the screen Arrow icon on send button changes to white but I want to change it to green. There is any posibility? 
http://uploadpie.com/pRAtz

**Comment by ksxkq** [comment]
it is just a .png. You can replace it with your owns.
The resource name : mq_ic_send_icon_gray.png   mq_ic_send_icon_white.png
