### ISSUE TITLE
【未读消息】在工单中回复用户，客户端调用获取未读消息接口获取不到未读消息

### ISSUE THREAD

**Issue by lolilicker** [Meiqia/MeiqiaSDK-Android#149]
用户给美洽留言后，留言自动进入美洽的工单列表而不是对话列表。如果在工单中回复用户，在android端调用getUnreadMessages接口，获取到的list一直是空的。

而在对话中回复离线的用户，android端通过此接口获取到的list内容是正确的。

iOS端目前还没试。

这样的话没法提示用户有新消息，达不到需求。

美洽sdk版本：3.3.6
升级到3.3.9之后也是这样。

**Comment by ksxkq** [comment]
4.4.0 已经修复

**Comment by ksxkq** [comment]
目前版本还不能获取工单的未读，下次更新会加上。

**Comment by ksxkq** [comment]
最新版已经加入
