### ISSUE TITLE
希望MQImageLoader是可以自定义然后设置的

### ISSUE THREAD

**Issue by lguipeng** [Meiqia/MeiqiaSDK-Android#155]
+100！！！

**Comment by bingoogolapple** [comment]
你项目里同时引入了多个图片加载库？

**Comment by lguipeng** [comment]
主要是fresco，用了美洽之后多了 picasso 导致我很郁闷

**Comment by lguipeng** [comment]
另外Fresco的适配可以参考 [FrescoImageAdapter](https://github.com/apache/incubator-weex/blob/master/android/commons/src/main/java/com/alibaba/weex/commons/adapter/FrescoImageAdapter.java)

**Comment by ksxkq** [comment]
v3.4.6 已经支持自定义

**Comment by lguipeng** [comment]
终于不用反射了==

**Comment by lguipeng** [comment]
我写了一个 FrescoMeiqiaImageAdapter， 可以使用 ImageVIiew 来显示，而不用 Fresco 的组件，目前使用OK，有空我可以提个 PR

**Comment by ksxkq** [comment]
> 我写了一个 FrescoMeiqiaImageLoader， 可以使用 ImageVIiew 来显示，而不用 Fresco 的组件，目前使用OK，有空我可以提个 PR
好的

**Comment by ksxkq** [comment]
> 我写了一个 FrescoMeiqiaImageLoader， 可以使用 ImageVIiew 来显示，而不用 Fresco 的组件，目前使用OK，有空我可以提个 PR

好的
