### ISSUE TITLE
NPE - 3.4.0

### ISSUE THREAD

**Issue by Yunfeng1u** [Meiqia/MeiqiaSDK-Android#163]
07-19 12:59:45.894 W/System.err( 5996): java.lang.NullPointerException: Attempt to invoke virtual method \'int java.lang.String.length()\' on a null object reference
07-19 12:59:45.895 W/System.err( 5996): at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
07-19 12:59:45.895 W/System.err( 5996): at org.json.JSONTokener.nextValue(JSONTokener.java:94)
07-19 12:59:45.895 W/System.err( 5996): at org.json.JSONObject.<init>(JSONObject.java:156)
07-19 12:59:45.896 W/System.err( 5996): at org.json.JSONObject.<init>(JSONObject.java:173)
07-19 12:59:45.896 W/System.err( 5996): at com.meiqia.core.bu.g(Unknown Source)
07-19 12:59:45.896 W/System.err( 5996): at com.meiqia.core.a.i(Unknown Source)
07-19 12:59:45.896 W/System.err( 5996): at com.meiqia.meiqiasdk.f.k.a(SourceFile)
07-19 12:59:45.896 W/System.err( 5996): at com.meiqia.meiqiasdk.f.k.<init>(SourceFile)

**Comment by bingoogolapple** [comment]
@ksxkq 你又写了个 bug 😄

**Comment by ksxkq** [comment]
这个问题能复现吗？ @Yunfeng1u
