### ISSUE TITLE
3.4.3版本崩溃

### ISSUE THREAD

**Issue by gaoneng1989** [Meiqia/MeiqiaSDK-Android#164]
Bugly收集的，堆栈信息如下：
<img width="708" alt="qq20170721-102434 2x" src="https://user-images.githubusercontent.com/8663660/28446720-3af1b28e-6dff-11e7-99b6-0fea0379173d.png">

**Comment by stackzhang** [comment]
Glide 加载图片是与 Activity/Fragment 的生命周期相关联的
_Glide源码_
<img width="656" alt="f2105e76-9bcc-4609-857d-af970f505d67" src="https://user-images.githubusercontent.com/8055636/28447868-336b09e6-6e06-11e7-810d-8fc36c2fd1d3.png">
建议修改com.meiqia.meiqiasdk.imageloader.MQGlideImageLoader.displayImage()方法，代码块加个try catch
![image](https://user-images.githubusercontent.com/8055636/28447956-dcf47934-6e06-11e7-99d8-b1a93e108ed6.png)
或者直接判断Activity生命周期

**Comment by ksxkq** [comment]
恩，下次更新会优化一下

**Comment by ksxkq** [comment]
v3.4.5 已经处理
