### ISSUE TITLE
3.4.4-MQPhotoPreviewActivity.savePic()方法存在bug

### ISSUE THREAD

**Issue by stackzhang** [Meiqia/MeiqiaSDK-Android#165]
![snip20170802_5](https://user-images.githubusercontent.com/8055636/28867302-2850d8a0-77a8-11e7-8445-981fd7afa92f.png)
![snip20170802_4](https://user-images.githubusercontent.com/8055636/28867113-975b8e80-77a7-11e7-949a-b21a0b337d17.png)

**Comment by ksxkq** [comment]
v3.4.5 已经处理
