### ISSUE TITLE
自定义界面

### ISSUE THREAD

**Issue by lucklyperson** [Meiqia/MeiqiaSDK-Android#166]
怎么实现自定义的聊天界面。比如在增加个控件等。

**Comment by bingoogolapple** [comment]
https://github.com/Meiqia/MeiqiaSDK-Android/blob/master/demo/src/main/java/com/meiqia/meiqiasdk/demo/CustomizedMQConversationActivity.java

**Comment by lucklyone** [comment]
我想在标题栏和会话列表之间添加一个布局文件，如下layout_show_goods：
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="@color/color_white"
    android:paddingTop="10dp">

    <ImageView
        android:id="@+id/iv"
        android:layout_width="50dp"
        android:layout_height="50dp"
        android:layout_marginBottom="10dp"
        android:layout_marginLeft="10dp"
        android:src="@mipmap/shao" />

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginLeft="15dp"
        android:layout_toRightOf="@+id/iv"
        android:orientation="vertical">

        <TextView
            android:id="@+id/tv_tip"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="一个手机模型,已包装"
            android:textColor="@color/text_color_title_or_important"
            android:textSize="14sp" />

        <TextView
            android:id="@+id/tv_price"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="￥20"
            android:textColor="@color/ui_main_color"
            android:textSize="14sp" />

        <TextView
            android:id="@+id/tv_status"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="交易前聊一聊"
            android:textColor="@color/text_color_hint"
            android:textSize="@dimen/small_text_size" />
    </LinearLayout>

</RelativeLayout>

Activity中的添加布局的代码：
  View view = LayoutInflater.from(this).inflate(R.layout.layout_show_goods, null);
        RelativeLayout relativeLayout = new RelativeLayout(this);
        relativeLayout.addView(view);
        RelativeLayout rl = (RelativeLayout) findViewById(R.id.chat_body_rl);
        RelativeLayout.LayoutParams layoutParams = new 
       RelativeLayout.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT, 
       ViewGroup.LayoutParams.WRAP_CONTENT);
        layoutParams.addRule(RelativeLayout.ABOVE, R.id.swipe_refresh_layout);
        rl.addView(relativeLayout, layoutParams);


但是并没有效果。

**Comment by lucklyone** [comment]
另一种方式：
        View view = LayoutInflater.from(this).inflate(R.layout.layout_show_goods, null);
        RelativeLayout rl = (RelativeLayout) findViewById(R.id.chat_body_rl);
        RelativeLayout.LayoutParams layoutParams = new 
        RelativeLayout.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT, 
        ViewGroup.LayoutParams.WRAP_CONTENT);
        layoutParams.addRule(RelativeLayout.ABOVE, R.id.swipe_refresh_layout);
        rl.addView(view, layoutParams);
另一种方式
         View view = LayoutInflater.from(this).inflate(R.layout.layout_show_goods, null);
        RelativeLayout rl = (RelativeLayout) findViewById(R.id.chat_body_rl);
        RelativeLayout.LayoutParams layoutParams = new 
        RelativeLayout.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT, 
        ViewGroup.LayoutParams.WRAP_CONTENT);
        layoutParams.addRule(RelativeLayout.ABOVE, R.id.swipe_refresh_layout);
        view.setLayoutParams(layoutParams);
        rl.addView(view);

试过的这几种方式都没有效果。不知道问题出在了哪儿

**Comment by ksxkq** [comment]
启动的时候要启动你那个 Activity 才行，可以看看 demo

**Comment by lucklyone** [comment]
肯定启动了哈，你可以新建一个Activity试试。

**Comment by ksxkq** [comment]
加群，然后把你代码发来看一下
