### ISSUE TITLE
为什么每次绑定用户id就报未知错误？（部分机型直接崩掉）startActivity(new MQIntentBuilder(this)                 .setCustomizedId(userId)                 .build());

### ISSUE THREAD

**Issue by lihong01** [Meiqia/MeiqiaSDK-Android#176]

**Comment by 18710891669** [comment]
![361921403399506577](https://user-images.githubusercontent.com/15627485/32269930-e5074b96-bf2e-11e7-8747-28e29636d9fa.png)
绑定用户id  错误截图

**Comment by 18710891669** [comment]
不绑定userId  直接启动就正常

**Comment by ksxkq** [comment]
你绑定 id 应该有点问题，换一个 id 绑定试一下
