### ISSUE TITLE
图片预览页的启动可能会报android.os.TransactionTooLargeException

### ISSUE THREAD

**Issue by reakingf** [Meiqia/MeiqiaSDK-Android#180]
由于进入图片预览页MQPhotoPickerPreviewActivity时是通过startActivityForResult的形式启动的，且会将遍历用户手机里图片的整个路径列表作为Intent的参数传给MQPhotoPickerPreviewActivity，
![image](https://user-images.githubusercontent.com/14134327/37274493-a3b419da-2617-11e8-8171-50ea5926ce29.png)
![image](https://user-images.githubusercontent.com/14134327/37274527-b765fe58-2617-11e8-8e29-5b0b90e7aefc.png)
所以，如果用户的手机里有非常多的图片，例如有1万张图片（现在的手机一般都不止32G，所以用户累计存到几千张甚至上万张图片都是有可能的），那么1万个图片地址的列表必定会超过intent的最大传输限制

**Comment by ksxkq** [comment]
[https://github.com/Meiqia/MeiqiaSDK-Android/releases/tag/v3.5.4](url)
