### ISSUE TITLE
java.lang.NoSuchMethodError, com.meiqia.meiqiasdk.imageloader.MQGlideImageLoader.displayImage

### ISSUE THREAD

**Issue by leagmain** [Meiqia/MeiqiaSDK-Android#182]
美洽sdk使用的glide版本还是3.x
但是我的工程使用的是最新的4.6.1
能否做下支持？

**Comment by ksxkq** [comment]
see
https://github.com/Meiqia/MeiqiaSDK-Android/commit/c076d006a61803b4ec15dde6dfa9a3a572b6fdf3
