### ISSUE TITLE
启动美洽客服400报错

### ISSUE THREAD

**Issue by Fish1230** [Meiqia/MeiqiaSDK-Android#197]
Intent intent = new MQIntentBuilder(mContext,MQConversationActivity.class)
//                                    .setClientInfo(clientInfo)
                                    .build();
                            mContext.startActivity(intent);
就报错400,path[track_id]，之前没出现过这个问题

**Comment by ksxkq** [comment]
之前绑定 id 错误，你卸载重装试一下
