### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest

### ISSUE THREAD

**Issue by imwhite** [Meiqia/MeiqiaSDK-Android#202]
04-22 12:21:34.003 E/AndroidRuntime( 5119): 	at com.meiqia.meiqiasdk.imageloader.MQGlideImageLoader.displayImage(MQGlideImageLoader.java:26)
04-22 12:21:34.003 E/AndroidRuntime( 5119): 	at com.meiqia.meiqiasdk.imageloader.MQImage.displayImage(MQImage.java:61)
04-22 12:21:34.003 E/AndroidRuntime( 5119): 	at com.meiqia.meiqiasdk.chatitem.MQBaseBubbleItem.fillContent(MQBaseBubbleItem.java:147)
04-22 12:21:34.003 E/AndroidRuntime( 5119): 	at com.meiqia.meiqiasdk.chatitem.MQBaseBubbleItem.setMessage(MQBaseBubbleItem.java:115)
04-22 12:21:34.003 E/AndroidRuntime( 5119): 	at com.meiqia.meiqiasdk.util.MQChatAdapter.getView(MQChatAdapter.java:144)

**Comment by ksxkq** [comment]
https://github.com/Meiqia/MeiqiaSDK-Android/blob/master/imageloader/MQGlideImageLoader4.java

**Comment by bashen1** [comment]
MQGlideImageLoader4 用了这个还是报相同错

**Comment by bashen1** [comment]
我这边的已经找到问题了，别的模块也引用了glide，版本统一下就过了
