### ISSUE TITLE
code 400 request data cannot be decrypted

### ISSUE THREAD

**Issue by alizbeo** [Meiqia/MeiqiaSDK-Android#225]
之前我们接入没有问题， 连接的上， 最近发现 Android 端 出现 code 400 request data cannot be decrypted， 我们没有任何关于接入的改动，而且iOS端没出现这个问题，要怎么解决？ 我们接的sdk3.6.2的最新版本
![Screenshot 2020-08-21 at 17 18 34](https://user-images.githubusercontent.com/30633856/90906715-59f3ab00-e3d2-11ea-91b5-f0e430093b33.png)

**Comment by ksxkq** [comment]
3.6.5 已解决
