### ISSUE TITLE
toast导致崩溃，3.6.3版本

### ISSUE THREAD

**Issue by mouxuefei** [Meiqia/MeiqiaSDK-Android#229]
Fatal Exception: java.lang.RuntimeException
Can't toast on a thread that has not called Looper.prepare()
android.widget.Toast$TN.<init> (Toast.java:491)
android.widget.Toast.makeText (Toast.java:301)
com.meiqia.meiqiasdk.activity.n.onFailure (MQConversationActivity.java:11)
com.meiqia.meiqiasdk.controller.h.onFailure (ControllerImpl.java:2)
com.meiqia.core.m.onFailure (未知来源:2)
com.meiqia.core.va.onFailure (未知来源:53)
com.meiqia.core.zb.a (未知来源:104)

**Comment by ksxkq** [comment]
最新版已修复
