### ISSUE TITLE
几个尚未 Material Design 的地方

### ISSUE THREAD

**Issue by xingrz** [Meiqia/MeiqiaSDK-Android#49]
3.1.0 改成 Material Design 了，可喜可贺！

几个不足的地方：
- 顶栏还不是 Toolbar，返回图标也不是 Material Design 的图标
- `MQTheme` 继承自老的 `@android:style/Theme.Light.NoTitleBar`，导致滚动条还是 2.X 的风格。建议改成 AppCompat 里的 `@style/Theme.AppCompat.Light.NoActionBar`

**Comment by bingoogolapple** [comment]
@xingrz 目前还有些用户在用 Eclipse 并且没有使用 v7 包，暂时还不能全部 Material Design
