### ISSUE TITLE
建议把Activity的逻辑的布局单独抽出来做成一个View

### ISSUE THREAD

**Issue by storezhang** [Meiqia/MeiqiaSDK-Android#5]
好处：把界面交给用户自己处理而不用担心用户会有过多的逻辑处理，这样可以让用户的界面更加统一（比如配色什么的）
![qq 20151223104210](https://cloud.githubusercontent.com/assets/4278758/11970216/e2927be0-a961-11e5-87ec-009390675457.jpg)

**Comment by PeterJiung** [comment]
建议用Fragment来实现
