### ISSUE TITLE
MQConversationActivity 内存泄漏

### ISSUE THREAD

**Issue by ONEWateR** [Meiqia/MeiqiaSDK-Android#91]
> com.meiqia.meiqiasdk.activity.MQConversationActivity has leaked:
* GC ROOT static com.meiqia.meiqiasdk.util.MQAudioRecorderManager.sInstance
* references com.meiqia.meiqiasdk.util.MQAudioRecorderManager.mCallback
* references com.meiqia.meiqiasdk.widget.MQRecorderKeyboardLayout.mContext
* leaks com.meiqia.meiqiasdk.activity.MQConversationActivity instance

检测信息来自 LeakCanary

**Comment by bingoogolapple** [comment]
@ONEWateR 谢谢反馈，下一个版本改

**Comment by bingoogolapple** [comment]
MQAudioRecorderManager不应该做成单例，当时搞成了单例造成的
